### ISSUE TITLE
"on" and "off"

### ISSUE THREAD

**Issue by paultoben** [Supergiovane/node-red-contrib-boolean-logic-ultimate#17]
It would be awesome if string "on" evaluated to true and string "off" evaluated to false. This would be great for use with home automation platforms (especially home assistant).

**Comment by Supergiovane** [comment]
Hi Paul
a "Hello", or "Hey, i appreciate the node, can you please..." should be the first sentence for requesting something to a developer of free and open source code.
**node-red-contrib-boolean-logic-ultimate@1.0.37** is out with the change you requested.
Please STAR my node. 
Thanks.

**Comment by noumenon272** [comment]
These nodes are super useful - I definitely appreciate your work on these. They make home home automation programming much easier. 

some additional boolean pairs would be a great addition for home automation. 
motion: active/inactive mapping to true/false
contact: closed/open mapping to true/false

the one hangup with closed/open mapping is that it kind of depends on if something is normally open or normally closed. I could see wanting an exterior window to be normally closed and a bathroom door to be normally open.

also, I use hubitat, and the nodes by fblackburn - https://flows.nodered.org/node/node-red-contrib-hubitat
which send the values under msg.payload.value rather than msg.payload. It would be nice to be able to specify the payload address, as it is I have to move everything to msg.payload.

finally, it would also be nice to be able to set the input count with msg.count (or similar). This would be useful when creating subflows and the count could be set external to the subflow or in an environmental variable.

anyway, the nodes are great. These are just some ideas and my dream wishlist from a home automation perspective. thanks for all your work on this.

**Comment by Supergiovane** [comment]
Hi Noumenon. 
i’ll take a look. Please leave me some time because i’m currently “out of order” due to covid.

**Comment by noumenon272** [comment]
Thanks! I hope you feel better. COVID sucks.

**Comment by Supergiovane** [comment]
Hi
Done. 
node-red-contrib-boolean-logic-ultimate@1.0.54 is out.
Please check if it works. I've updated the README as well.

**Comment by noumenon272** [comment]
great! thats awesome, thanks! I’ll do some testing on it, but this should hopefully help simplify my flows.

It might be nice to have the output payload address be the same as the input. so if msg.payload.value was used it would output there and not at msg.payload.

also, I know my primary use case is for normally open contact sensors, so having closed=true and open=false works better for me. Thoughts?

thanks again

**Comment by Supergiovane** [comment]
Hi
yes, but i must obey to what all users asks. In my experience, "open" is often "true", because it's assimilable to an alert. Homekit, KNX and others do the same.

**Comment by noumenon272** [comment]
hmmm. will invert ultimate switch open to closed? maybe that would work for me.

Also, looking at invert ultimate, I can only change the name. it doesn’t have a box to change the input address. (the readme says it should have that now)

**Comment by Supergiovane** [comment]
Hi
Sorry, fixed the invert node in the 1.0.55
For the payload output, i must think about that and do some checks...
